// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: "https://h7cblclvpjh2tmqjyl6r7a6zkm.appsync-api.us-east-1.amazonaws.com/graphql",
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: "da2-jde763k35rhhtemcxjulcmlpre",
      
        }
    }
};

// const config = { API: {
//     GraphQL: {
//       endpoint: 'https://gs6p5szmajg47d5hje2qctk7be.appsync-api.ap-south-1.amazonaws.com/graphql',
//       region: 'ap-south-1',
//       defaultAuthMode: 'apiKey',
//       apiKey: 'da2-kz2darudxreprel4piyot6mefu'
//     }
//   }}
  export default config